FROM mcr.microsoft.com/mssql/server:2017-latest AS build
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=1337entropy

WORKDIR /tmp

COPY Backup2020.bak .
COPY restore-backup.sql .

RUN /opt/mssql/bin/sqlservr & sleep 10 \
	&& /opt/mssql-tools/bin/sqlcmd -S localhost -U SA "1337entropy" -i /tmp/restore-backup.sql \
	&& pkill sqlservr

FROM mcr.microsoft.com/mssql/server:2017-latest AS final

ENV ACCEPT_EULA=Y

COPY --from=build /var/opt/mssql/data /var/opt/mssql/data 
